## Modify these settings
PREFIX=arm-elf
GCC_VERSION=-4.6

## System commands definitions
CC=$(PREFIX)-gcc$(GCC_VERSION)
LD=$(CC)
AR=$(PREFIX)-ar
AS=$(PREFIX)-as
OBJCOPY=$(PREFIX)-objcopy
OBJDUMP=$(PREFIX)-objdump
