## Modify these settings
PREFIX=arm-none-eabi
GCC_VERSION=

## System commands definitions
CC=$(PREFIX)-gcc$(GCC_VERSION)
LD=$(CC)
AR=$(PREFIX)-ar
AS=$(PREFIX)-as
OBJCOPY=$(PREFIX)-objcopy
OBJDUMP=$(PREFIX)-objdump
NM=$(PREFIX)-nm
