.TH "clock.h" 3 "Wed Mar 21 2012" "rfLPC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
clock.h \- 
.PP
Clock initialization and defines\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'nxp/LPC17xx\&.h'\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBrflpc_clock_divider_t\fP { \fBRFLPC_CCLK_4\fP =  0, \fBRFLPC_CCLK\fP =  1, \fBRFLPC_CCLK_2\fP =  2, \fBRFLPC_CCLK_8\fP =  3 }"
.br
.RI "\fIThis enums defines the different cpu clock dividers for use as peripheral clocks\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "uint32_t \fBrflpc_clock_get_system_clock\fP ()"
.br
.RI "\fIreturns the system clock in Hz \fP"
.ti -1c
.RI "void \fBrflpc_clock_init\fP (void)"
.br
.RI "\fIinit the PLL0 to clock the board at its operational speed\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Clock initialization and defines\&. 


.PP
Definition in file \fBclock\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for rfLPC from the source code\&.
