.TH "Clock" 3 "Wed Mar 21 2012" "rfLPC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Clock \- 
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBrflpc_clock_divider_t\fP { \fBRFLPC_CCLK_4\fP =  0, \fBRFLPC_CCLK\fP =  1, \fBRFLPC_CCLK_2\fP =  2, \fBRFLPC_CCLK_8\fP =  3 }"
.br
.RI "\fIThis enums defines the different cpu clock dividers for use as peripheral clocks\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "uint32_t \fBrflpc_clock_get_system_clock\fP ()"
.br
.RI "\fIreturns the system clock in Hz \fP"
.ti -1c
.RI "void \fBrflpc_clock_init\fP (void)"
.br
.RI "\fIinit the PLL0 to clock the board at its operational speed\&. \fP"
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBrflpc_clock_divider_t\fP"

.PP
This enums defines the different cpu clock dividers for use as peripheral clocks\&. (See doc p\&. 57) 
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIRFLPC_CCLK_4 \fP\fP
Divide the CPU clock by 4\&. 
.TP
\fB\fIRFLPC_CCLK \fP\fP
Use the CPU clock\&. .PP
.nf
      .fi
.PP
 
.TP
\fB\fIRFLPC_CCLK_2 \fP\fP
Divide the CPU clock by 2\&. 
.TP
\fB\fIRFLPC_CCLK_8 \fP\fP
Divide the CPU clock by 8\&. 
.PP
Definition at line 38 of file clock\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void \fBrflpc_clock_init\fP (void)"

.PP
init the PLL0 to clock the board at its operational speed\&. This function will use the defines:
.IP "\(bu" 2
\fBRFLPC_CLOCK_USE_MAIN_OSCILLATOR\fP
.IP "\(bu" 2
\fBRFLPC_CLOCK_MAIN_OSCILLATOR_FREQUENCY\fP
.IP "\(bu" 2
\fBRFLPC_CLOCK_INPUT_DIVIDER\fP
.IP "\(bu" 2
\fBRFLPC_CLOCK_PLL_MULTIPLIER\fP
.IP "\(bu" 2
\fBRFLPC_CLOCK_CPU_DIVIDER\fP 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for rfLPC from the source code\&.
