.TH "config.h" 3 "Wed Mar 21 2012" "rfLPC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config.h \- 
.PP
Platform independent configuration options\&.  

.SH SYNOPSIS
.br
.PP
.SS "Defines"

.PP
.RI "\fBStack configuration\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "#define \fBRFLPC_STACK_SIZE\fP   1024"
.br
.RI "\fIsize of the stack in bytes \fP"
.in -1c
.in -1c
.PP
.RI "\fBInterrupt configuration\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "#define \fBRFLPC_IRQ_DEBUG_ENABLE\fP"
.br
.RI "\fIIf this constant is defined, then freeze the device on unhandled interrupt\&. \fP"
.ti -1c
.RI "#define \fBRFLPC_IRQn_COUNT\fP   (PLL1_IRQn + 16 +1)"
.br
.RI "\fIThis is the size of the interrupt vector\&. \fP"
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
Platform independent configuration options\&. 


.PP
Definition in file \fBconfig\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for rfLPC from the source code\&.
