.TH "debug.h" 3 "Wed Mar 21 2012" "rfLPC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
debug.h \- 
.PP
Debug functions such as delay and stack dump\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'drivers/leds\&.h'\fP
.br
\fC#include 'config\&.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBRFLPC_DELAY\fP(c)"
.br
.RI "\fIwait until a counter reaches c\&. \fP"
.ti -1c
.RI "#define \fBRFLPC_STOP\fP(l, c)"
.br
.RI "\fIStops execution by an infinite loop, switching between led pattern l and its opposite\&. \fP"
.ti -1c
.RI "#define \fBRFLPC_DUMP_STACK\fP()"
.br
.RI "\fIDumps 64 bytes from the current value of the stack pointer\&. \fP"
.ti -1c
.RI "#define \fBRFLPC_ASSERT\fP(cond)   do { if (!(cond)) { \fBRFLPC_STOP\fP(0, 50000); } } while (0)"
.br
.RI "\fIAsserts a condition\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Debug functions such as delay and stack dump\&. 


.PP
Definition in file \fBdebug\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for rfLPC from the source code\&.
