.TH "Peripheral drivers" 3 "Wed Mar 21 2012" "rfLPC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Peripheral drivers \- 
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBLEDs\fP"
.br
.RI "\fIProvides function to control onboard leds\&. \fP"
.ti -1c
.RI "\fBEthernet\fP"
.br
.RI "\fIMost of the defines are directly derived from the user manual of the LPC17xx or the PHY interface datasheet\&. \fP"
.ti -1c
.RI "\fBGeneral Purpose DMA\fP"
.br
.ti -1c
.RI "\fBGeneral Purpose Input Output (GPIO)\fP"
.br
.ti -1c
.RI "\fBRepetitive Interrupt Timer\fP"
.br
.RI "\fIThis timer provide a simple mean to get a repetitive interrupt\&. \fP"
.ti -1c
.RI "\fBSPI\fP"
.br
.ti -1c
.RI "\fBSystem tick timer\fP"
.br
.RI "\fIThis driver allows the use of the system tick timer\&. \fP"
.ti -1c
.RI "\fBTimers\fP"
.br
.RI "\fIAll four timers provides the same functionality\&. \fP"
.ti -1c
.RI "\fBUART\fP"
.br
.RI "\fIThis is the driver for the UART0/2/3\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for rfLPC from the source code\&.
