.TH "gpio.h" 3 "Wed Mar 21 2012" "rfLPC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gpio.h \- 
.PP
GPIO peripheral driver\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include '\&.\&./nxp/LPC17xx\&.h'\fP
.br
\fC#include '\&.\&./tools\&.h'\fP
.br
\fC#include '\&.\&./pinconf\&.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBRFLPC_GPIO_BASE\fP(gpio_number)   \fBTOKEN_PASTE\fP(LPC_GPIO, gpio_number)"
.br
.RI "\fIMacro used to convert a digit in the corresponding pointer\&. \fP"
.ti -1c
.RI "#define \fBrflpc_gpio_set_pin_mode_input\fP(gpio, pin)"
.br
.RI "\fISets a pin to input mode\&. \fP"
.ti -1c
.RI "#define \fBrflpc_gpio_set_pin_mode_output\fP(gpio, pin)"
.br
.RI "\fISets a pin to output mode\&. \fP"
.ti -1c
.RI "#define \fBrflpc_gpio_set_pin\fP(gpio, pin)"
.br
.RI "\fISet a pin (put a logical 1 on it) \fP"
.ti -1c
.RI "#define \fBrflpc_gpio_clr_pin\fP(gpio, pin)"
.br
.RI "\fIClear a pin (put a logical 0 on it) \fP"
.ti -1c
.RI "#define \fBrflpc_gpio_set_pins_from_mask\fP(gpio, mask)"
.br
.RI "\fISet multiple pins from a mask\&. \fP"
.ti -1c
.RI "#define \fBrflpc_gpio_clr_pins_from_mask\fP(gpio, mask)"
.br
.RI "\fIClean multiple pins from a mask\&. \fP"
.ti -1c
.RI "#define \fBrflpc_gpio_set_pin_val\fP(gpio, pin, val)"
.br
.RI "\fISets the value of a pin (0 or 1) \fP"
.ti -1c
.RI "#define \fBrflpc_gpio_set_val\fP(gpio, val, mask)"
.br
.RI "\fISets the value of multiple pins of a given port from a mask and a value\&. \fP"
.ti -1c
.RI "#define \fBrflpc_gpio_get_pin\fP(gpio, pin)   (\fBRFLPC_GPIO_BASE\fP(gpio)->FIOMASK = ~= (1 << (pin)), (\fBRFLPC_GPIO_BASE\fP(gpio)->FIOPIN >> (pin)) & 1)"
.br
.RI "\fIGets the value of a pin\&. \fP"
.ti -1c
.RI "#define \fBrflpc_gpio_get_val\fP(gpio)   (\fBRFLPC_GPIO_BASE\fP(gpio)->FIOMASK = 0, \fBRFLPC_GPIO_BASE\fP(gpio)->FIOPIN)"
.br
.RI "\fIGets the value of the entire port\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBrflpc_gpio_use_pin\fP (int gpio, int pin)"
.br
.RI "\fIConfigures the multi-purpose pins of the CM3 so that it uses a given GPIO pin\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
GPIO peripheral driver\&. 


.PP
Definition in file \fBgpio\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for rfLPC from the source code\&.
