.TH "leds.h" 3 "Wed Mar 21 2012" "rfLPC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leds.h \- 
.PP
On board LEDs peripheral driver\&.  

.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./config\&.h'\fP
.br
\fC#include 'gpio\&.h'\fP
.br

.SS "Defines"

.PP
.RI "\fBLEDs defines\fP"
.br
This values can be used to set/clear leds in the driver functions 
.PP
.in +1c
.in +1c
.ti -1c
.RI "#define \fBRFLPC_LED_1\fP   (1 << \fBRFLPC_LED_1_PIN\fP)"
.br
.RI "\fILED 1\&. \fP"
.ti -1c
.RI "#define \fBRFLPC_LED_2\fP   (1 << \fBRFLPC_LED_2_PIN\fP)"
.br
.RI "\fILED 2\&. \fP"
.ti -1c
.RI "#define \fBRFLPC_LED_3\fP   (1 << \fBRFLPC_LED_3_PIN\fP)"
.br
.RI "\fILED 3\&. \fP"
.ti -1c
.RI "#define \fBRFLPC_LED_4\fP   (1 << \fBRFLPC_LED_4_PIN\fP)"
.br
.RI "\fILED 4\&. \fP"
.in -1c
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBrflpc_led_init\fP ()"
.br
.RI "\fIInits the GPIO port to use the leds\&. \fP"
.ti -1c
.RI "static void \fBrflpc_led_set\fP (uint32_t l)"
.br
.RI "\fITurns the given led(s) on\&. \fP"
.ti -1c
.RI "static void \fBrflpc_led_clr\fP (uint32_t l)"
.br
.RI "\fIClears the given led(s) (turn them off) \fP"
.ti -1c
.RI "static void \fBrflpc_led_val\fP (uint32_t l)"
.br
.RI "\fITurns on the leds included in the mask\&. \fP"
.ti -1c
.RI "static void \fBrflpc_led_binary_value\fP (uint8_t v)"
.br
.RI "\fITurns the led to reflect a binary 4 digit number\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
On board LEDs peripheral driver\&. 


.PP
Definition in file \fBleds\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for rfLPC from the source code\&.
