.TH "memcpy.h" 3 "Wed Mar 21 2012" "rfLPC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
memcpy.h \- 
.PP
An implementation of memcpy\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stddef\&.h>\fP
.br

.SS "Functions"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "void * \fBmemcpy\fP (void *dest, const void *src, size_t n)"
.br
.RI "\fICopies memory from one buffer to another\&. \fP"
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
An implementation of memcpy\&. 


.PP
Definition in file \fBmemcpy\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for rfLPC from the source code\&.
