.TH "memset.h" 3 "Wed Mar 21 2012" "rfLPC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
memset.h \- 
.PP
An implementation of memset\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stddef\&.h>\fP
.br

.SS "Functions"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "void * \fBmemset\fP (void *dest, int c, size_t n)"
.br
.RI "\fIFills the first n bytes of the memory area pointed to by dest with the constant byte c\&. \fP"
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
An implementation of memset\&. 


.PP
Definition in file \fBmemset\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for rfLPC from the source code\&.
