.TH "Pin configuration" 3 "Wed Mar 21 2012" "rfLPC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pin configuration \- 
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBrflpc_pin_mode_t\fP { \fBRFLPC_PIN_MODE_RESISTOR_PULL_UP\fP, \fBRFLPC_PIN_MODE_REPEATER\fP, \fBRFLPC_PIN_MODE_RESISTOR_NONE\fP, \fBRFLPC_PIN_MODE_RESISTOR_PULL_DOWN\fP }"
.br
.RI "\fIPin mode\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBrflpc_pin_set\fP (int port, int pin, int function, \fBrflpc_pin_mode_t\fP mode, int opendrain)"
.br
.RI "\fISets the operational mode for a given pin on a given port\&. \fP"
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBrflpc_pin_mode_t\fP"

.PP
Pin mode\&. Affects the behavior only if the pin is used as input 
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIRFLPC_PIN_MODE_RESISTOR_PULL_UP \fP\fP
The pin has pull-up resistor enabled\&. .PP
.nf
   .fi
.PP
 
.TP
\fB\fIRFLPC_PIN_MODE_REPEATER \fP\fP
The pin has repeater mode enabled\&. .PP
.nf
      .fi
.PP
 
.TP
\fB\fIRFLPC_PIN_MODE_RESISTOR_NONE \fP\fP
The pin has neither pull-up nor pull-down\&. 
.TP
\fB\fIRFLPC_PIN_MODE_RESISTOR_PULL_DOWN \fP\fP
The pin has pull-down resistor enabled\&. .PP
.nf
 .fi
.PP
 
.PP
Definition at line 37 of file pinconf\&.h\&.
.SH "Function Documentation"
.PP 
.SS "static void \fBrflpc_pin_set\fP (intport, intpin, intfunction, \fBrflpc_pin_mode_t\fPmode, intopendrain)\fC [inline, static]\fP"

.PP
Sets the operational mode for a given pin on a given port\&. \fBNote:\fP
.RS 4
See the LPC17xx user manual to get a description of functions as the functions are dependent on the pin
.RE
.PP
\fBParameters:\fP
.RS 4
\fIport\fP The port of the pin (0\&.\&.4) 
.br
\fIpin\fP The pin (0\&.\&.31) 
.br
\fIfunction\fP How the pin is used (0\&.\&.3)\&. 
.br
\fImode\fP The pin mode (see \fBrflpc_pin_mode_t\fP) 
.br
\fIopendrain\fP Control the open drain mode for pins used as output\&. 0 for normal mode (no open drain), 1 for open drain\&. 
.RE
.PP

.PP
Definition at line 55 of file pinconf\&.h\&.
.PP
Referenced by rflpc_gpio_use_pin()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for rfLPC from the source code\&.
