.TH "pinconf.h" 3 "Wed Mar 21 2012" "rfLPC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pinconf.h \- 
.PP
Multi-purpose pins configuration made easy\&.  

.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBrflpc_pin_mode_t\fP { \fBRFLPC_PIN_MODE_RESISTOR_PULL_UP\fP, \fBRFLPC_PIN_MODE_REPEATER\fP, \fBRFLPC_PIN_MODE_RESISTOR_NONE\fP, \fBRFLPC_PIN_MODE_RESISTOR_PULL_DOWN\fP }"
.br
.RI "\fIPin mode\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBrflpc_pin_set\fP (int port, int pin, int function, \fBrflpc_pin_mode_t\fP mode, int opendrain)"
.br
.RI "\fISets the operational mode for a given pin on a given port\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Multi-purpose pins configuration made easy\&. 


.PP
Definition in file \fBpinconf\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for rfLPC from the source code\&.
