.TH "printf.h" 3 "Wed Mar 21 2012" "rfLPC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
printf.h \- 
.PP
An implementation of formated output\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBprintf\fP (const char *format,\&.\&.\&.)"
.br
.RI "\fIFormated output function\&. \fP"
.ti -1c
.RI "void \fBrflpc_printf_set_putchar\fP (int(*putchar_func)(int c))"
.br
.RI "\fISets the internal function pointer that is used by \fBprintf\fP to output a character\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
An implementation of formated output\&. 


.PP
Definition in file \fBprintf\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for rfLPC from the source code\&.
