.TH "rflpc_eth_descriptor_t" 3 "Wed Mar 21 2012" "rfLPC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rflpc_eth_descriptor_t \- 
.PP
This structure holds a descriptor which describes the fragment received or sent by the ethernet DMA\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ethernet\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t * \fBpacket\fP"
.br
.RI "\fIpointer to buffer where the ethernet frame (or frame fragment) is stored \fP"
.ti -1c
.RI "uint32_t \fBcontrol\fP"
.br
.RI "\fIControl word where we find data buffer size and other information relative to reception/emission of the buffer\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This structure holds a descriptor which describes the fragment received or sent by the ethernet DMA\&. 
.PP
Definition at line 105 of file ethernet\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint32_t \fBrflpc_eth_descriptor_t::control\fP"

.PP
Control word where we find data buffer size and other information relative to reception/emission of the buffer\&. Word format for reception:
.IP "\(bu" 2
Bits 10:0 : Size of the buffer pointed by packet (-1 encoded)
.IP "\(bu" 2
Bit 31 : IRQ on reception enabled/disabled
.PP
.PP
Word format for transmission:
.IP "\(bu" 2
Bits 10:0 : Size of the buffer to transmit (-1 encoded)
.IP "\(bu" 2
Bit 26 : Override\&. If true, bits 30:27 will override the default values in MAC registers\&. Otherwise, bits 29:27 will be ignored
.IP "\(bu" 2
Bit 27 : Huge (jumbo) frame
.IP "\(bu" 2
Bit 28 : Pad short frame to 64 bytes
.IP "\(bu" 2
Bit 29 : Append CRC to the frame
.IP "\(bu" 2
Bit 30 : Last fragment
.IP "\(bu" 2
Bit 31 : IRQ on transmission enabled/disabled 
.PP

.PP
Definition at line 124 of file ethernet\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for rfLPC from the source code\&.
