.TH "rflpc_eth_rx_status_t" 3 "Wed Mar 21 2012" "rfLPC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rflpc_eth_rx_status_t \- 
.PP
This structure holds the reception status associated to a descriptor\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ethernet\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBstatus_info\fP"
.br
.RI "\fIReceive status return flags\&. \fP"
.ti -1c
.RI "uint32_t \fBstatus_hash_crc\fP"
.br
.RI "\fIhash CRC calculated from source and destination address\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This structure holds the reception status associated to a descriptor\&. 
.PP
Definition at line 129 of file ethernet\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint32_t \fBrflpc_eth_rx_status_t::status_hash_crc\fP"

.PP
hash CRC calculated from source and destination address\&. .IP "\(bu" 2
Bits 8:0 : CRC calcultated from the source address
.IP "\(bu" 2
Bits 24:16 : CRC calcultated from the destination address 
.PP

.PP
Definition at line 153 of file ethernet\&.h\&.
.SS "uint32_t \fBrflpc_eth_rx_status_t::status_info\fP"

.PP
Receive status return flags\&. .IP "\(bu" 2
Bits 10:0 : Size of the received data (-1 encoded)
.IP "\(bu" 2
Bit 18 : Control frame
.IP "\(bu" 2
Bit 19 : VLAN frame
.IP "\(bu" 2
Bit 20 : Fail frame filter\&. The remainder of the frame will be discarded
.IP "\(bu" 2
Bit 21 : Multicast frame
.IP "\(bu" 2
Bit 22 : Broadcast frame
.IP "\(bu" 2
Bit 23 : CRC error
.IP "\(bu" 2
Bit 24 : Symbol error reported by PHY
.IP "\(bu" 2
Bit 25 : Length Error
.IP "\(bu" 2
Bit 26 : Range error
.IP "\(bu" 2
Bit 27 : Alignement erro
.IP "\(bu" 2
Bit 28 : Receive overrun
.IP "\(bu" 2
Bit 29 : No more descriptor and the frame is to big to fit in the data buffer
.IP "\(bu" 2
Bit 30 : Last flag\&. This is the last fragment of the frame
.IP "\(bu" 2
Bit 31 : Error occured\&. 
.PP

.PP
Definition at line 148 of file ethernet\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for rfLPC from the source code\&.
