.TH "rflpc17xx.h" 3 "Wed Mar 21 2012" "rfLPC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rflpc17xx.h \- 
.PP
Main header file\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'nxp/LPC17xx\&.h'\fP
.br
\fC#include 'nxp/core_cm3\&.h'\fP
.br
\fC#include 'config\&.h'\fP
.br
\fC#include 'clock\&.h'\fP
.br
\fC#include 'debug\&.h'\fP
.br
\fC#include 'interrupt\&.h'\fP
.br
\fC#include 'pinconf\&.h'\fP
.br
\fC#include 'profiling\&.h'\fP
.br
\fC#include 'tinylibc/printf\&.h'\fP
.br
\fC#include 'tinylibc/memcpy\&.h'\fP
.br
\fC#include 'tinylibc/memset\&.h'\fP
.br
\fC#include 'tinylibc/setjmp\&.h'\fP
.br
\fC#include 'drivers/eth_const\&.h'\fP
.br
\fC#include 'drivers/ethernet\&.h'\fP
.br
\fC#include 'drivers/gpio\&.h'\fP
.br
\fC#include 'drivers/leds\&.h'\fP
.br
\fC#include 'drivers/rit\&.h'\fP
.br
\fC#include 'drivers/spi\&.h'\fP
.br
\fC#include 'drivers/sys_tick_timer\&.h'\fP
.br
\fC#include 'drivers/timer\&.h'\fP
.br
\fC#include 'drivers/uart\&.h'\fP
.br
\fC#include 'drivers/dma\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Main header file\&. 

Can be used to include every needed headers at once\&. 
.PP
Definition in file \fBrflpc17xx\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for rfLPC from the source code\&.
