.TH "sys_tick_timer.h" 3 "Wed Mar 21 2012" "rfLPC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sys_tick_timer.h \- 
.PP
System tick timer device driver\&.  

.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./interrupt\&.h'\fP
.br
\fC#include '\&.\&./nxp/LPC17xx\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBrflpc_sys_timer_init\fP ()"
.br
.RI "\fIinitializes the system timer \fP"
.ti -1c
.RI "static void \fBrflpc_sys_timer_start\fP ()"
.br
.RI "\fIstarts the system timer \fP"
.ti -1c
.RI "static void \fBrflpc_sys_timer_stop\fP ()"
.br
.RI "\fIstops the system timer \fP"
.ti -1c
.RI "static void \fBrflpc_sys_timer_set_callback\fP (\fBrflpc_irq_handler_t\fP c)"
.br
.RI "\fIsets the callback for the timer interrupt \fP"
.ti -1c
.RI "void \fBrflpc_sys_timer_set_period\fP (uint32_t micros_time)"
.br
.RI "\fIinitializes the timer with a given period (in µs) This automatically starts the timer even if it was stopped\&. \fP"
.ti -1c
.RI "void \fBrflpc_sys_timer_set_tick_period\fP (uint32_t ticks)"
.br
.RI "\fIinitializes the timer with a given tick count This automatically starts the timer even if it was stopped\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
System tick timer device driver\&. 


.PP
Definition in file \fBsys_tick_timer\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for rfLPC from the source code\&.
