.TH "Base system" 3 "Wed Mar 21 2012" "rfLPC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Base system \- 
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBPin configuration\fP"
.br
.ti -1c
.RI "\fBClock\fP"
.br
.ti -1c
.RI "\fBLIBC tiny subset\fP"
.br
.RI "\fIThe rflpc library implement a very small subset of the libc\&. \fP"
.ti -1c
.RI "\fBMBED Platform configuration\fP"
.br
.RI "\fIThe following defines are used to configure the library to use with the MBED\&. \fP"
.ti -1c
.RI "\fBDebug macro\fP"
.br
.RI "\fIUseful macro to use for debuggin purpose\&. \fP"
.ti -1c
.RI "\fBInterruption management\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for rfLPC from the source code\&.
