.TH "todo" 3 "Wed Mar 21 2012" "rfLPC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
.IP "\fBGlobal \fBrflpc_dma_start\fP (rflpc_dma_channel_t channel, void *dest, const void *src, uint32_t size)\fP" 1c
Handle size > 0xFFF  
.IP "\fBGlobal \fBrflpc_gpio_use_pin\fP (int gpio, int pin)\fP" 1c
Add more parameters to allow the configuration of pull-up pull-down and/or open drain mode  
.IP "\fBGroup \fBuart\fP \fP" 1c
Allow fine configuration for the UART\&. Just have to calculate divider and multiplier depending on cpu clock and desired speed\&.
.PP
.PP

