.TH "uart.h" 3 "Wed Mar 21 2012" "rfLPC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uart.h \- 
.PP
UART0 driver\&.  

.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./nxp/LPC17xx\&.h'\fP
.br
\fC#include '\&.\&./interrupt\&.h'\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBrflpc_uart_t\fP { \fBRFLPC_UART0\fP =  0, \fBRFLPC_UART2\fP =  2, \fBRFLPC_UART3\fP =  3 }"
.br
.RI "\fIConstants that represents the UART port you want to use in uart driver functions\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBrflpc_uart_init\fP (\fBrflpc_uart_t\fP uart_num)"
.br
.RI "\fIInits the UART e, using 11520 baud, 8 bits data, no parity and 1 stop bit\&. \fP"
.ti -1c
.RI "void \fBrflpc_uart_putchar\fP (\fBrflpc_uart_t\fP uart_num, char c)"
.br
.RI "\fISends a byte to the uart\&. \fP"
.ti -1c
.RI "int \fBrflpc_uart_byte_available\fP (\fBrflpc_uart_t\fP uart_num)"
.br
.RI "\fITest the reception FIFO\&. \fP"
.ti -1c
.RI "char \fBrflpc_uart_getchar\fP (\fBrflpc_uart_t\fP uart_num)"
.br
.RI "\fIGets a character from the uart\&. \fP"
.ti -1c
.RI "void \fBrflpc_uart_set_rx_callback\fP (\fBrflpc_uart_t\fP uart_num, \fBrflpc_irq_handler_t\fP callback)"
.br
.RI "\fISets the uart rx callback\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
UART0 driver\&. 


.PP
Definition in file \fBuart\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for rfLPC from the source code\&.
