/* This file is part of rflpc. Copyright 2010-2011 Michael Hauspie
 *
 * rflpc is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * rflpc is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with rflpc.  If not, see <http://www.gnu.org/licenses/>.
 */
/** @file */
/*
 Author: Michael Hauspie <michael.hauspie@univ-lille1.fr>
 Created:
 Time-stamp: <2011-07-13 14:18:07 (hauspie)>
 */
/** @defgroup system Base system */

/** @defgroup drivers Peripheral drivers */

/** @defgroup clock Clock
 *  @ingroup system
 * */

/** @defgroup leds LEDs
 *  @ingroup drivers
 * */

/** @defgroup eth Ethernet
 *  @ingroup drivers
 * */

/** @defgroup libc LIBC tiny subset
 * @ingroup system
 * The rflpc library implement a very small subset of the libc.
 * Actually, only function on which a call may be automatically generated by gcc are implemented
 */
