OUTPUT_NAME=$(shell basename $(shell pwd))
SRC=$(wildcard *.c)
OBJS=$(SRC:.c=.o)

# Modify this variable at your own risk
#RFLPC_DIR=/home/deep/dev/pje/hauspie-rflpc-df9d632
RFLPC_DIR=/home/deep/dev/pji/rflpc
include $(RFLPC_DIR)/Makefile.in

