rfLPC: Timers
Timers
Peripheral drivers
All four timers provides the same functionality.
Enumerations
enum rflpc_timer_t {
RFLPC_TIMER0 = 0,
RFLPC_TIMER1 = 1,
RFLPC_TIMER2 = 2,
RFLPC_TIMER3 = 3
}
Value to use for the timer value in functions.
enum rflpc_timer_match_t {
RFLPC_TIMER_MATCH0 = 0,
RFLPC_TIMER_MATCH1 = 1,
RFLPC_TIMER_MATCH2 = 2,
RFLPC_TIMER_MATCH3 = 3
}
Match registers for interrupt generation.
enum {
RFLPC_TIMER_IRQ_ON_MATCH = 1,
RFLPC_TIMER_RESET_ON_MATCH = 2,
RFLPC_TIMER_STOP_ON_MATCH = 4
}
Options for interrupt generation.
Functions
static LPC_TIM_TypeDef * rflpc_timer_base (rflpc_timer_t timer)
This function is used by the driver to convert the timer id to the base address of its configuration register.
static void rflpc_timer_enable (rflpc_timer_t timer)
Power and clock the given timer.
static void rflpc_timer_disable (rflpc_timer_t timer)
disable the given timer
static void rflpc_timer_set_clock (rflpc_timer_t timer, rflpc_clock_divider_t divider)
Sets the cpu clock divider for a given timer.
static void rflpc_timer_set_callback (rflpc_timer_t timer, rflpc_irq_handler_t callback)
Sets the timer interrupt callback.
static void rflpc_timer_start (rflpc_timer_t timer)
starts the given timer.
static void rflpc_timer_stop (rflpc_timer_t timer)
Stops the timer.
static void rflpc_timer_reset (rflpc_timer_t timer)
Resets the timer.
static uint32_t rflpc_timer_get_counter (rflpc_timer_t timer)
Returns the timer counter value.
static uint32_t rflpc_timer_get_pre_scale_counter (rflpc_timer_t timer)
Returns the prescale counter value.
static uint32_t rflpc_timer_get_pre_scale_register (rflpc_timer_t timer)
Returns the value of the prescale register.
static void rflpc_timer_set_counter (rflpc_timer_t timer, uint32_t value)
Sets the timer counter value.
static void rflpc_timer_set_pre_scale_counter (rflpc_timer_t timer, uint32_t value)
Sets the prescale counter value.
static void rflpc_timer_set_pre_scale_register (rflpc_timer_t timer, uint32_t value)
Sets the value of the prescale register.
static void rflpc_timer_set_match_value (rflpc_timer_t timer, rflpc_timer_match_t match_register, uint32_t match_value)
Set the match register value for a given timer.
static void rflpc_timer_set_irq_on_match (rflpc_timer_t timer, rflpc_timer_match_t match_register, uint32_t options)
Enable IRQ generation when the timer counter reaches the value of a match register.
static void rflpc_timer_reset_irq (rflpc_timer_t timer, rflpc_timer_match_t match_register)
Reset the irq for a given match register.
static int rflpc_timer_test_irq (rflpc_timer_t timer, rflpc_timer_match_t match_register)
Check if an interrupt has been generated for a given match register.
Detailed Description
All four timers provides the same functionality.
The prescale counter is incremented at each timer clock tick. When the prescale counter reaches the prescale register value, the counter is incremented. The value of the counter can then be used as time value or match against four match registers to trigger an interrupt.
Enumeration Type Documentation
anonymous enum
Options for interrupt generation.
Enumerator:
RFLPC_TIMER_IRQ_ON_MATCH
Trigger an interrupt when counter matches the match register.
RFLPC_TIMER_RESET_ON_MATCH
Reset the timer when counter matches the match register.
RFLPC_TIMER_STOP_ON_MATCH
Stop the timer when the counter matches the match register.
Definition at line 68 of file timer.h.
enum rflpc_timer_match_t
Match registers for interrupt generation.
Enumerator:
RFLPC_TIMER_MATCH0
Match register 0.
RFLPC_TIMER_MATCH1
Match register 1.
RFLPC_TIMER_MATCH2
Match register 2.
RFLPC_TIMER_MATCH3
Match register 3.
Definition at line 58 of file timer.h.
enum rflpc_timer_t
Value to use for the timer value in functions.
Enumerator:
RFLPC_TIMER0
Timer 0.
RFLPC_TIMER1
Timer 1.
RFLPC_TIMER2
Timer 2.
RFLPC_TIMER3
Timer 3.
Definition at line 48 of file timer.h.
Function Documentation
static LPC_TIM_TypeDef* rflpc_timer_base (rflpc_timer_t timer) [inline, static]
This function is used by the driver to convert the timer id to the base address of its configuration register.
Parameters:
timer The timer to get
Returns:
LPC_TIM_TypeDef*
Definition at line 82 of file timer.h.
References RFLPC_TIMER0, RFLPC_TIMER1, RFLPC_TIMER2, and RFLPC_TIMER3.
Referenced by rflpc_timer_get_counter(), rflpc_timer_get_pre_scale_counter(), rflpc_timer_get_pre_scale_register(), rflpc_timer_reset(), rflpc_timer_reset_irq(), rflpc_timer_set_counter(), rflpc_timer_set_irq_on_match(), rflpc_timer_set_match_value(), rflpc_timer_set_pre_scale_counter(), rflpc_timer_set_pre_scale_register(), rflpc_timer_start(), rflpc_timer_stop(), and rflpc_timer_test_irq().
static void rflpc_timer_disable (rflpc_timer_t timer) [inline, static]
disable the given timer
Parameters:
timer
Definition at line 122 of file timer.h.
References RFLPC_TIMER0, RFLPC_TIMER1, RFLPC_TIMER2, and RFLPC_TIMER3.
static void rflpc_timer_enable (rflpc_timer_t timer) [inline, static]
Power and clock the given timer.
Parameters:
timer
Definition at line 101 of file timer.h.
References RFLPC_TIMER0, RFLPC_TIMER1, RFLPC_TIMER2, and RFLPC_TIMER3.
static uint32_t rflpc_timer_get_counter (rflpc_timer_t timer) [inline, static]
Returns the timer counter value.
This value is incremented each time the prescale counter matches the prescale register.
Parameters:
timer
Returns:
Definition at line 220 of file timer.h.
References rflpc_timer_base().
static uint32_t rflpc_timer_get_pre_scale_counter (rflpc_timer_t timer) [inline, static]
Returns the prescale counter value.
This value is incremented at each clock cycle.
Parameters:
timer
Returns:
Definition at line 233 of file timer.h.
References rflpc_timer_base().
static uint32_t rflpc_timer_get_pre_scale_register (rflpc_timer_t timer) [inline, static]
Returns the value of the prescale register.
This register contains the number of clock cycle needed to increment the timer counter. That is, at each clock cycle, the prescale counter is incrementer and when it reaches the prescale register, the timer counter is incremented.
Parameters:
timer
Returns:
Definition at line 248 of file timer.h.
References rflpc_timer_base().
static void rflpc_timer_reset (rflpc_timer_t timer) [inline, static]
Resets the timer.
Parameters:
timer
Definition at line 205 of file timer.h.
References rflpc_timer_base().
static void rflpc_timer_reset_irq (rflpc_timer_t timer, rflpc_timer_match_t match_register) [inline, static]
Reset the irq for a given match register.
Parameters:
timer
match_register
Definition at line 332 of file timer.h.
References rflpc_timer_base().
static void rflpc_timer_set_callback (rflpc_timer_t timer, rflpc_irq_handler_t callback) [inline, static]
Sets the timer interrupt callback.
Also enables timer interrupt to be received.
Parameters:
timer
callback
Definition at line 168 of file timer.h.
References rflpc_irq_enable(), and rflpc_irq_set_handler().
static void rflpc_timer_set_clock (rflpc_timer_t timer, rflpc_clock_divider_t divider) [inline, static]
Sets the cpu clock divider for a given timer.
Parameters:
timer
divider
See also:
rflpc_clock_divider_t
Definition at line 144 of file timer.h.
References RFLPC_TIMER0, RFLPC_TIMER1, RFLPC_TIMER2, and RFLPC_TIMER3.
static void rflpc_timer_set_counter (rflpc_timer_t timer, uint32_t value) [inline, static]
Sets the timer counter value.
This value is incremented each time the prescale counter matches the prescale register.
Parameters:
timer
value
Definition at line 262 of file timer.h.
References rflpc_timer_base().
static void rflpc_timer_set_irq_on_match (rflpc_timer_t timer, rflpc_timer_match_t match_register, uint32_t options) [inline, static]
Enable IRQ generation when the timer counter reaches the value of a match register.
Parameters:
timer
match_register
options a bitwise ORed value of RFLPC_TIMER_IRQ_ON_MATCH, RFLPC_TIMER_RESET_ON_MATCH and RFLPC_TIMER_STOP_ON_MATCH
Returns:
Definition at line 319 of file timer.h.
References rflpc_timer_base().
static void rflpc_timer_set_match_value (rflpc_timer_t timer, rflpc_timer_match_t match_register, uint32_t match_value) [inline, static]
Set the match register value for a given timer.
Interrupt can be generated when timer counter reaches a match register's value
Parameters:
timer
match_register
match_value
Returns:
Definition at line 305 of file timer.h.
References rflpc_timer_base().
static void rflpc_timer_set_pre_scale_counter (rflpc_timer_t timer, uint32_t value) [inline, static]
Sets the prescale counter value.
This value is incremented at each clock cycle.
Parameters:
timer
value
Definition at line 275 of file timer.h.
References rflpc_timer_base().
static void rflpc_timer_set_pre_scale_register (rflpc_timer_t timer, uint32_t value) [inline, static]
Sets the value of the prescale register.
This register contains the number of clock cycle needed to increment the timer counter. That is, at each clock cycle, the prescale counter is incrementer and when it reaches the prescale register, the timer counter is incremented.
Parameters:
timer
value
Definition at line 290 of file timer.h.
References rflpc_timer_base().
static void rflpc_timer_start (rflpc_timer_t timer) [inline, static]
starts the given timer.
This does not modify timer register value. It just starts to count
Parameters:
timer
Definition at line 184 of file timer.h.
References rflpc_timer_base().
static void rflpc_timer_stop (rflpc_timer_t timer) [inline, static]
Stops the timer.
Does not modify timer registers value
Parameters:
timer
Definition at line 196 of file timer.h.
References rflpc_timer_base().
static int rflpc_timer_test_irq (rflpc_timer_t timer, rflpc_timer_match_t match_register) [inline, static]
Check if an interrupt has been generated for a given match register.
Parameters:
timer
match_register
Returns:
true if an interrupt is pending for the given match register
Definition at line 345 of file timer.h.
References rflpc_timer_base().